"""
sc9_IPYNB_LAUNCHER.py — Execute Generated .ipynb in PLAXIS (Button 3)
=====================================================================
Reads the PLAXIS API notebook generated by sc3/sc5 and executes each
code cell directly in the current PLAXIS Python environment where
the g_i object is available.

Called from Excel via:
  RunPython "import scripts.sc9_IPYNB_LAUNCHER as l; l.main()"
"""

from pathlib import Path
import json
import traceback
import xlwings as xw

try:
    from .notebook_paths import notebook_path_for_workbook
except ImportError:  # pragma: no cover - supports direct script execution
    from notebook_paths import notebook_path_for_workbook


# ── Progress cell (SC9, shares B5 with SC6 — mirrors SC8/SC6 pattern) ──
# assign_sequence!B5 is blank in the template (verified 2026-09-08 on
# v0.7.14 EXAMPLE 2: B5/D2/D4 blank, SC5 table starts at B6). In the
# FULL chain (scFULL button) SC6 hands B5 to SC9: SC9's first write
# overwrites SC6's done text. Each script runs its own 0–100 so
# standalone runs stay truthful. Never raises — progress must not
# break runs.
PROGRESS_SHEET = 'assign_sequence'
PROGRESS_CELL = 'B5'
PROGRESS_BAR_WIDTH = 10
_SPIN_CHARS = ('|', '/', '-', '\\')
_spin_idx = 0


def _spin():
    """Return next spinner character (hybrid indeterminate pulse)."""
    global _spin_idx
    ch = _SPIN_CHARS[_spin_idx % len(_SPIN_CHARS)]
    _spin_idx += 1
    return ch


def _bar(frac):
    """Return '██████░░░░ 55%' for frac in [0, 1] (clamped)."""
    frac = max(0.0, min(1.0, float(frac)))
    filled = int(round(frac * PROGRESS_BAR_WIDTH))
    return ('█' * filled + '░' * (PROGRESS_BAR_WIDTH - filled)
            + f' {int(round(frac * 100))}%')


def _set_progress(wb, msg):
    """Write *msg* to assign_sequence!B5. False/None clears. Never raises."""
    try:
        sheet = wb.sheets[PROGRESS_SHEET]
        try:
            app = wb.app
            prev = app.screen_updating
            app.screen_updating = True
            sheet.range(PROGRESS_CELL).value = (
                msg if msg else None)
            app.screen_updating = prev
        except Exception:
            sheet.range(PROGRESS_CELL).value = (
                msg if msg else None)
    except Exception:
        pass


def main():
    """
    Find and execute the generated PLAXIS notebook in-process.
    Called via: RunPython "import scripts.sc9_IPYNB_LAUNCHER as l; l.main()"
    """
    # ── Get workbook ──
    try:
        wb = xw.Book.caller()
    except Exception:
        _cwd = Path.cwd()
        _xl_files = list(_cwd.glob('*.xlsm'))
        if not _xl_files:
            _xl_files = list(_cwd.parent.glob('*.xlsm'))
        if not _xl_files:
            raise FileNotFoundError(f"No .xlsm file found in {_cwd}")
        wb = xw.Book(str(_xl_files[0]))

    # ── Find notebook ──
    nb_path = notebook_path_for_workbook(wb)
    if not nb_path.exists():
        raise FileNotFoundError(
            f"sc9: No notebook found at {nb_path}. Run sc3/sc5 first."
        )

    print(f"sc9: Loading {nb_path.name}...")
    _set_progress(wb, f"sc9: {_spin()} WORKING — loading notebook…")

    # ── Read notebook ──
    with open(nb_path, 'r', encoding='utf-8') as f:
        notebook = json.load(f)

    cells = notebook.get('cells', [])
    code_cells = [c for c in cells if c.get('cell_type') == 'code']
    print(f"sc9: {len(code_cells)} code cells to execute.")
    n_cells = len(code_cells)
    if not n_cells:
        _set_progress(wb, "sc9: done — no code cells")
        print("sc9: Done. 0 cells executed, 0 failed.")
        return

    # ── Execute each code cell ──
    success = 0
    failed = 0
    try:
        for i, cell in enumerate(code_cells, 1):
            source = ''.join(cell.get('source', []))
            if not source.strip():
                continue

            # Show first line as progress indicator
            first_line = source.strip().split('\n')[0][:80]
            print(f"sc9: [{i}/{n_cells}] {first_line}")
            _set_progress(
                wb,
                f"sc9: {_spin()} WORKING — cell {i}/{n_cells} "
                f"{_bar(i / n_cells)}")

            try:
                exec(source, globals())
                success += 1
            except Exception:
                failed += 1
                print(f"sc9: ERROR in cell {i}:")
                traceback.print_exc()
                _set_progress(
                    wb, f"sc9: FAILED — cell {i}/{n_cells}: {first_line}")
                # Stop on first error — don't continue with broken state
                break
    finally:
        # Never leave a stale WORKING banner: crash → FAILED, else the
        # success path below already set done/failed text.
        try:
            cur = wb.sheets[PROGRESS_SHEET].range(PROGRESS_CELL).value
        except Exception:
            cur = None
        if isinstance(cur, str) and 'WORKING' in cur.upper():
            _set_progress(wb, "sc9: FAILED — see console for detail")

    if not failed:
        _set_progress(
            wb,
            f"sc9: done — {success}/{n_cells} cells {_bar(1.0)}")
    print(f"sc9: Done. {success} cells executed, {failed} failed.")


if __name__ == '__main__':
    main()
